# Generated by Django 4.1 on 2022-09-07 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_rename_comments_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='user_profile',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='name',
        ),
    ]
