# Generated by Django 4.1 on 2022-09-07 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_rename_post_comment_user_profile_remove_comment_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='name',
            field=models.CharField(default=0, max_length=80),
            preserve_default=False,
        ),
    ]
