# Generated by Django 4.1 on 2022-09-08 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0006_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.CharField(default=0, max_length=80),
            preserve_default=False,
        ),
    ]
